---
- hosts: all
  gather_facts: False
  pre_tasks:
    - name: Install python for ansible
      raw: sudo apt-get -y install python-simplejson
  tasks:
    - name: Create web user
      user: name={{web_user}}
