---
- include: init.yml
- hosts: loadbalancer
  vars:
    ssl_cert: gochat2019.crt # UPDATE THIS
    ssl_key: gochat2018.key # UPDATE THIS
  pre_tasks:
    - name: Create ssl folder
      file: path=/etc/ssl/{{project_name}} group={{web_user}} owner={{web_user}} mode=6755 state=directory
    - name: Copy SSL certificates
      copy:
        src: "{{item.src}}"
        dest: "{{item.dest}}"
        owner: "{{web_user}}"
        group: "{{web_user}}"
        mode: "{{755}}"
      with_items:
        - { src: "ssl/{{ssl_cert}}", dest: "/etc/ssl/{{project_name}}/{{ssl_cert}}" }
        - { src: "ssl/{{ssl_key}}", dest: "/etc/ssl/{{project_name}}/{{ssl_key}}" }

  roles:
    - role: ansible-role-nginx
      nginx_user: "{{web_user}}"
      nginx_sites:
        default:
         - listen 80
         - listen 443 ssl
         - server_name {{server_name}}
         - location / {
             proxy_pass http://backend;
           }
      nginx_configs:
        ssl:
          - ssl_certificate_key /etc/ssl/{{project_name}}/{{ssl_key}}
          - ssl_certificate /etc/ssl/{{project_name}}/{{ssl_cert}}
        proxy:
          - proxy_set_header Host $host
          - proxy_set_header X-Real-IP $remote_addr
          - proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for
          - proxy_set_header X-Forwarded-Proto $scheme
        upstream:
          #  server 10.134.4.171:5000 weight=2;
          - upstream backend {server 0.0.0.0:5000; server 0.0.0.0:5000;} # UPDATE THIS
